name: CI lab_01 (unittest)

on:
  push:
    paths:
      - 'lab_01/**'
      - '.github/workflows/lab_01-unittest.yml'
  pull_request:
    paths:
      - 'lab_01/**'
      - '.github/workflows/lab_01-unittest.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # unittest is stdlib; no extra install needed
          pip install pytest  # (optional) only if some helper is in requirements

      - name: Run unittest for lab_01 only
        env:
          PYTHONPATH: lab_01/src
        run: |
          python -m unittest discover -s lab_01/tests -p "test_*unittest.py" -v
